### PR TITLE
Couple of suggestions for master branch

### PR DESCRIPTION
**Pull request by CristinaLS**
See comments in each commit :)

### CODE REVIEW

**Comment by EdwardMLewis** [comment]
@CristinaLS first commit is great - great shout.
Second commit - you tried it? Does it work fine?

**Comment by CristinaLS** [comment]
@EdwardMLewis Second commit: it worked indeed - but I should try it again as this was done before your last edits :)

**Comment by EdwardMLewis** [comment]
@CristinaLS ok, can you edit the pull request to just include the CAN data input placeholder for now? I want to see if we can change a pull request or if you'll have to make a new one. Thanks.

**Comment by EdwardMLewis** [comment]
@CristinaLS ok, i'm going to accept your code, i think it's more elegant than mine.

**Pull request merged**
